
import './globals.css'
import Navbar from "@/components/navbar/Navbar";
import { Provider } from "@/context/Context";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const pathname = usePathname()

  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {pathname.includes("/login")? null : <Navbar/>}
          {children}
        </body>
      </Provider>
    </html>
  );
}
